version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass mypass
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=mypass
      - REDIS_DATABASES=1

volumes:
  redis-data: